### ISSUE TITLE
MaterialRefreshLayout 不能实例化

### ISSUE THREAD

**Issue by RedRiverCN** [385841539/RecycleviewStaggered#3]
3-10 03:02:02.220 6693-6693/com.example.myrecyclviewdemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.example.myrecyclviewdemo, PID: 6693
                                                                            java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myrecyclviewdemo/com.example.myrecyclviewdemo.MainActivity}: java.lang.RuntimeException: MaterialRefreshLayout can't be  null
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
                                                                                at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                at android.os.Looper.loop(Looper.java:164)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
                                                                             Caused by: java.lang.RuntimeException: MaterialRefreshLayout can't be  null

**Comment by littlelovelysheep** [comment]
我也遇到类似的问题了
